backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # where uploaded files go in repo
public_folder: "/images/uploads"    # how site references them

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }