backend:
  name: github
  repo: AlexGoldsteinFilm/AlexGoldsteinFilm
  branch: main

publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }