backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "albums"
    label: "Albums"
    folder: "content/albums"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }