backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dfy80qmy3
    api_key: "381665872177331"

# Where album data files are saved in your repo
collections:
  - name: albums
    label: Portfolio Albums
    label_singular: Album
    folder: _data/albums
    create: true
    slug: "{{slug}}"
    extension: json
    format: json
    sort: "date:desc"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: Description, name: description, widget: text }
      - label: Photos
        name: photos
        widget: list
        summary: "{{fields.alt}}"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Alt Text, name: alt, widget: string }
          - { label: Use as Cover, name: is_cover, widget: boolean, default: false }